give @p rb:bluegem
give @p rb:curseofmurder
give @p rb:darkmatter
give @p rb:dustyemerald
give @p rb:elementalessence
give @p rb:firegrassroot
give @p rb:flamearray
give @p rb:lightfromleaves
give @p rb:oceancrystal
give @p rb:redgem
give @p rb:skillscroll
give @p rb:thickblood
give @p rb:tigerspear
give @p rb:whetstone
give @p rb:stranger
give @p rb:swallowsky
give @p rb:hearthdiresword
give @p rb:nightlost
give @p rb:nightmare
give @p rb:goldencity
give @p rbb:oldalchemicalpan
give @p rbb:bluegem
give @p rbb:firegrass